using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NormPuckModel
{
    [RealtimeProperty(1, false, true)]
    private int _team;

    [RealtimeProperty(2, false, true)]
    private int _side;

    [RealtimeProperty(3, true, true)]
    private int _collisionCount;

    [RealtimeProperty(6, true, true)]
    private bool _isOnTable;

    [RealtimeProperty(7, true, false)]
    private float _velocity;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NormPuckModel : RealtimeModel {
    public int team {
        get {
            return _teamProperty.value;
        }
        set {
            if (_teamProperty.value == value) return;
            _teamProperty.value = value;
            InvalidateUnreliableLength();
            FireTeamDidChange(value);
        }
    }
    
    public int side {
        get {
            return _sideProperty.value;
        }
        set {
            if (_sideProperty.value == value) return;
            _sideProperty.value = value;
            InvalidateUnreliableLength();
            FireSideDidChange(value);
        }
    }
    
    public int collisionCount {
        get {
            return _collisionCountProperty.value;
        }
        set {
            if (_collisionCountProperty.value == value) return;
            _collisionCountProperty.value = value;
            InvalidateReliableLength();
            FireCollisionCountDidChange(value);
        }
    }
    
    public bool isOnTable {
        get {
            return _isOnTableProperty.value;
        }
        set {
            if (_isOnTableProperty.value == value) return;
            _isOnTableProperty.value = value;
            InvalidateReliableLength();
            FireIsOnTableDidChange(value);
        }
    }
    
    public float velocity {
        get {
            return _velocityProperty.value;
        }
        set {
            if (_velocityProperty.value == value) return;
            _velocityProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NormPuckModel model, T value);
    public event PropertyChangedHandler<int> teamDidChange;
    public event PropertyChangedHandler<int> sideDidChange;
    public event PropertyChangedHandler<int> collisionCountDidChange;
    public event PropertyChangedHandler<bool> isOnTableDidChange;
    
    public enum PropertyID : uint {
        Team = 1,
        Side = 2,
        CollisionCount = 3,
        IsOnTable = 6,
        Velocity = 7,
    }
    
    #region Properties
    
    private UnreliableProperty<int> _teamProperty;
    
    private UnreliableProperty<int> _sideProperty;
    
    private ReliableProperty<int> _collisionCountProperty;
    
    private ReliableProperty<bool> _isOnTableProperty;
    
    private ReliableProperty<float> _velocityProperty;
    
    #endregion
    
    public NormPuckModel() : base(null) {
        _teamProperty = new UnreliableProperty<int>(1, _team);
        _sideProperty = new UnreliableProperty<int>(2, _side);
        _collisionCountProperty = new ReliableProperty<int>(3, _collisionCount);
        _isOnTableProperty = new ReliableProperty<bool>(6, _isOnTable);
        _velocityProperty = new ReliableProperty<float>(7, _velocity);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _collisionCountProperty.UnsubscribeCallback();
        _isOnTableProperty.UnsubscribeCallback();
        _velocityProperty.UnsubscribeCallback();
    }
    
    private void FireTeamDidChange(int value) {
        try {
            teamDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireSideDidChange(int value) {
        try {
            sideDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireCollisionCountDidChange(int value) {
        try {
            collisionCountDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIsOnTableDidChange(bool value) {
        try {
            isOnTableDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _teamProperty.WriteLength(context);
        length += _sideProperty.WriteLength(context);
        length += _collisionCountProperty.WriteLength(context);
        length += _isOnTableProperty.WriteLength(context);
        length += _velocityProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _teamProperty.Write(stream, context);
        writes |= _sideProperty.Write(stream, context);
        writes |= _collisionCountProperty.Write(stream, context);
        writes |= _isOnTableProperty.Write(stream, context);
        writes |= _velocityProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Team: {
                    changed = _teamProperty.Read(stream, context);
                    if (changed) FireTeamDidChange(team);
                    break;
                }
                case (uint) PropertyID.Side: {
                    changed = _sideProperty.Read(stream, context);
                    if (changed) FireSideDidChange(side);
                    break;
                }
                case (uint) PropertyID.CollisionCount: {
                    changed = _collisionCountProperty.Read(stream, context);
                    if (changed) FireCollisionCountDidChange(collisionCount);
                    break;
                }
                case (uint) PropertyID.IsOnTable: {
                    changed = _isOnTableProperty.Read(stream, context);
                    if (changed) FireIsOnTableDidChange(isOnTable);
                    break;
                }
                case (uint) PropertyID.Velocity: {
                    changed = _velocityProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _team = team;
        _side = side;
        _collisionCount = collisionCount;
        _isOnTable = isOnTable;
        _velocity = velocity;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
